
    const textFilter = ref("")
    const contentfilter = ref({})
    const Data = ref([{
    id: 51,
    name: "86: Eighty Six",
    img: "/img/86.png",
    genre: ["Action", "Drame", "Mecha"],
    nbSaison: 2,
    status: {
      status: "none",
    },
    studio: "A-1 Pictures",
  },
  {
    id: 52,
    name: "Made in Abyss",
    img: "/img/mia.png",
    genre: ["Aventure", "Mystère", "Dark Fantasy"],
    nbSaison: 2,
    status: {
      status: "none",
    },
    studio: "Kinema Citrus",
  },
  {
    id: 53,
    name: "Lord of the Mysteries",
    img: "/img/lotm.png",
    genre: ["Action", "Aventure", "Surnaturel"],
    nbSaison: 1,
    status: {
      status: "prevu",
      date: "Été 2025",
    },
    studio: "B.C MAY PICTURES",
  },
  {
    id: 54,
    name: "Takopi's Original Sin",
    img: "/img/takopi.png",
    genre: ["Drame", "Psychologique", "Tranche de vie"],
    nbSaison: 1,
    status: {
      status: "prevu",
      date: "TBA",
    },
    studio: "TBA",
  },
  {
    id: 55,
    name: "Violet Evergarden",
    img: "/img/violet.png",
    genre: ["Drame", "Tranche de vie", "Fantasy"],
    nbSaison: 1,
    status: {
      status: "none",
    },
    studio: "Kyoto Animation",
  },
  {
    id: 1,
    name: "Chainsaw Man",
    img: "/img/chainsaw-man.jpg",
    genre: ["Action", "Gore"],
    nbSaison: 1,
    status: { status: "none" },
    studio: "MAPPA",
  },
  {
    id: 2,
    name: "One Piece",
    img: "/img/one-piece.jpg",
    genre: ["Aventure", "Action"],
    nbSaison: 1,
    status: {
      status: "on air",
      heure: "09:30",
      jour: "Dimanche",
      lastSaison: 1,
      lastEpisode: 1116,
    },
    studio: "Toei Animation",
  },
  {
    id: 3,
    name: "Solo Leveling",
    img: "/img/solo-leveling.jpg",
    genre: ["Action", "Fantasy"],
    nbSaison: 2,
    status: { status: "prevu", date: "Janvier 2025" },
    studio: "A-1 Pictures",
  },
  {
    id: 4,
    name: "Demon Slayer",
    img: "/img/demon-slayer.jpg",
    genre: ["Action", "Historique"],
    nbSaison: 4,
    status: { status: "prevu", date: "2026" },
    studio: "ufotable",
  },
  {
    id: 5,
    name: "Jujutsu Kaisen",
    img: "/img/jujutsu-kaisen.jpg",
    genre: ["Action", "Surnaturel"],
    nbSaison: 2,
    status: { status: "none" },
    studio: "MAPPA",
  },
  {
    id: 6,
    name: "Bleach: TYBW",
    img: "/img/bleach.jpg",
    genre: ["Action", "Shonen"],
    nbSaison: 3,
    status: {
      status: "on air",
      heure: "16:00",
      jour: "Samedi",
      lastSaison: 3,
      lastEpisode: 8,
    },
    studio: "Pierrot",
  },
  {
    id: 7,
    name: "Spy x Family",
    img: "/img/spy-x-family.jpg",
    genre: ["Comédie", "Action"],
    nbSaison: 2,
    status: { status: "none" },
    studio: "WIT Studio",
  },
  {
    id: 8,
    name: "Blue Lock",
    img: "/img/blue-lock.jpg",
    genre: ["Sport", "Thriller"],
    nbSaison: 2,
    status: {
      status: "on air",
      heure: "23:00",
      jour: "Samedi",
      lastSaison: 2,
      lastEpisode: 4,
    },
    studio: "Eight Bit",
  },
  {
    id: 9,
    name: "My Hero Academia",
    img: "/img/mha.jpg",
    genre: ["Action", "Super-héros"],
    nbSaison: 7,
    status: { status: "none" },
    studio: "Bones",
  },
  {
    id: 10,
    name: "Oshi no Ko",
    img: "/img/oshi-no-ko.jpg",
    genre: ["Drame", "Musique"],
    nbSaison: 2,
    status: { status: "none" },
    studio: "Doga Kobo",
  },
  {
    id: 11,
    name: "Frieren",
    img: "/img/frieren.jpg",
    genre: ["Aventure", "Fantasy"],
    nbSaison: 1,
    status: { status: "none" },
    studio: "Madhouse",
  },
  {
    id: 12,
    name: "Kaiju No. 8",
    img: "/img/kaiju-8.jpg",
    genre: ["Action", "Sci-Fi"],
    nbSaison: 2,
    status: { status: "prevu", date: "2025" },
    studio: "Production I.G",
  },
  {
    id: 13,
    name: "Attack on Titan",
    img: "/img/aot.jpg",
    genre: ["Action", "Drame"],
    nbSaison: 4,
    status: { status: "none" },
    studio: "MAPPA",
  },
  {
    id: 14,
    name: "Mushoku Tensei",
    img: "/img/mushoku.jpg",
    genre: ["Isekai", "Aventure"],
    nbSaison: 2,
    status: { status: "none" },
    studio: "Studio Bind",
  },
  {
    id: 15,
    name: "Black Clover",
    img: "/img/black-clover.jpg",
    genre: ["Action", "Magie"],
    nbSaison: 1,
    status: { status: "prevu", date: "TBA" },
    studio: "Pierrot",
  },
  {
    id: 16,
    name: "Vinland Saga",
    img: "/img/vinland.jpg",
    genre: ["Action", "Historique"],
    nbSaison: 2,
    status: { status: "none" },
    studio: "MAPPA",
  },
  {
    id: 17,
    name: "Hunter x Hunter",
    img: "/img/hxh.jpg",
    genre: ["Aventure", "Action"],
    nbSaison: 1,
    status: { status: "none" },
    studio: "Madhouse",
  },
  {
    id: 18,
    name: "Hell's Paradise",
    img: "/img/hells-paradise.jpg",
    genre: ["Action", "Surnaturel"],
    nbSaison: 2,
    status: { status: "prevu", date: "2025" },
    studio: "MAPPA",
  },
  {
    id: 19,
    name: "Naruto Shippuden",
    img: "/img/naruto.jpg",
    genre: ["Action", "Ninja"],
    nbSaison: 1,
    status: { status: "none" },
    studio: "Pierrot",
  },
  {
    id: 20,
    name: "Tower of God",
    img: "/img/tog.jpg",
    genre: ["Aventure", "Mystère"],
    nbSaison: 2,
    status: {
      status: "on air",
      heure: "21:00",
      jour: "Dimanche",
      lastSaison: 2,
      lastEpisode: 15,
    },
    studio: "The Answer Studio",
  },
  {
    id: 21,
    name: "Dr. Stone",
    img: "/img/dr-stone.jpg",
    genre: ["Sci-Fi", "Aventure"],
    nbSaison: 4,
    status: { status: "prevu", date: "Janvier 2025" },
    studio: "TMS Entertainment",
  },
  {
    id: 22,
    name: "Mob Psycho 100",
    img: "/img/mob.jpg",
    genre: ["Action", "Tranche de vie"],
    nbSaison: 3,
    status: { status: "none" },
    studio: "Bones",
  },
  {
    id: 23,
    name: "Shangri-La Frontier",
    img: "/img/slf.jpg",
    genre: ["Action", "Gaming"],
    nbSaison: 2,
    status: {
      status: "on air",
      heure: "17:00",
      jour: "Dimanche",
      lastSaison: 2,
      lastEpisode: 4,
    },
    studio: "C2C",
  },
  {
    id: 24,
    name: "Re:Zero",
    img: "/img/rezero.jpg",
    genre: ["Isekai", "Psychologique"],
    nbSaison: 3,
    status: {
      status: "on air",
      heure: "22:30",
      jour: "Mercredi",
      lastSaison: 3,
      lastEpisode: 6,
    },
    studio: "White Fox",
  },
  {
    id: 25,
    name: "Tokyo Ghoul",
    img: "/img/tokyo-ghoul.jpg",
    genre: ["Horreur", "Action"],
    nbSaison: 2,
    status: { status: "none" },
    studio: "Pierrot",
  },
  {
    id: 26,
    name: "Fullmetal Alchemist: B",
    img: "/img/fmab.jpg",
    genre: ["Action", "Drame"],
    nbSaison: 1,
    status: { status: "none" },
    studio: "Bones",
  },
  {
    id: 27,
    name: "Haikyu!!",
    img: "/img/haikyu.jpg",
    genre: ["Sport", "Comédie"],
    nbSaison: 4,
    status: { status: "none" },
    studio: "Production I.G",
  },
  {
    id: 28,
    name: "Blue Exorcist",
    img: "/img/blue-exorcist.jpg",
    genre: ["Action", "Démons"],
    nbSaison: 4,
    status: {
      status: "on air",
      heure: "23:30",
      jour: "Samedi",
      lastSaison: 4,
      lastEpisode: 5,
    },
    studio: "Studio VOLN",
  },
  {
    id: 29,
    name: "Fire Force",
    img: "/img/fire-force.jpg",
    genre: ["Action", "Surnaturel"],
    nbSaison: 3,
    status: { status: "prevu", date: "Avril 2025" },
    studio: "David Production",
  },
  {
    id: 30,
    name: "Steins;Gate",
    img: "/img/steins-gate.jpg",
    genre: ["Sci-Fi", "Thriller"],
    nbSaison: 1,
    status: { status: "none" },
    studio: "White Fox",
  },
  {
    id: 31,
    name: "Dandadan",
    img: "/img/dandadan.jpg",
    genre: ["Action", "Comédie"],
    nbSaison: 1,
    status: {
      status: "on air",
      heure: "18:00",
      jour: "Jeudi",
      lastSaison: 1,
      lastEpisode: 5,
    },
    studio: "Science SARU",
  },
  {
    id: 32,
    name: "Bleach",
    img: "/img/bleach-old.jpg",
    genre: ["Action", "Shonen"],
    nbSaison: 16,
    status: { status: "none" },
    studio: "Pierrot",
  },
  {
    id: 33,
    name: "Ranking of Kings",
    img: "/img/rok.jpg",
    genre: ["Aventure", "Fantasy"],
    nbSaison: 1,
    status: { status: "none" },
    studio: "WIT Studio",
  },
  {
    id: 34,
    name: "Dragon Ball Super",
    img: "/img/dbs.jpg",
    genre: ["Action", "Combat"],
    nbSaison: 1,
    status: { status: "none" },
    studio: "Toei Animation",
  },
  {
    id: 35,
    name: "Death Note",
    img: "/img/death-note.jpg",
    genre: ["Thriller", "Mystère"],
    nbSaison: 1,
    status: { status: "none" },
    studio: "Madhouse",
  },
  {
    id: 36,
    name: "One Punch Man",
    img: "/img/opm.jpg",
    genre: ["Action", "Parodie"],
    nbSaison: 3,
    status: { status: "prevu", date: "TBA" },
    studio: "J.C.Staff",
  },
  {
    id: 37,
    name: "Code Geass",
    img: "/img/code-geass.jpg",
    genre: ["Mecha", "Politique"],
    nbSaison: 2,
    status: { status: "none" },
    studio: "Sunrise",
  },
  {
    id: 38,
    name: "Sword Art Online",
    img: "/img/sao.jpg",
    genre: ["Action", "Isekai"],
    nbSaison: 4,
    status: { status: "none" },
    studio: "A-1 Pictures",
  },
  {
    id: 39,
    name: "The Rising of the Shield Hero",
    img: "/img/shield-hero.jpg",
    genre: ["Isekai", "Action"],
    nbSaison: 4,
    status: { status: "prevu", date: "2025" },
    studio: "Kinema Citrus",
  },
  {
    id: 40,
    name: "That Time I Got Reincarnated as a Slime",
    img: "/img/slime.jpg",
    genre: ["Isekai", "Fantasy"],
    nbSaison: 3,
    status: { status: "none" },
    studio: "Eight Bit",
  },
  {
    id: 41,
    name: "Classroom of the Elite",
    img: "/img/cote.jpg",
    genre: ["Psychologique", "Scolaire"],
    nbSaison: 4,
    status: { status: "prevu", date: "2025" },
    studio: "Lerche",
  },
  {
    id: 42,
    name: "Overlord",
    img: "/img/overlord.jpg",
    genre: ["Isekai", "Dark Fantasy"],
    nbSaison: 4,
    status: { status: "none" },
    studio: "Madhouse",
  },
  {
    id: 43,
    name: "Bleach: TYBW Part 3",
    img: "/img/bleach-3.jpg",
    genre: ["Action"],
    nbSaison: 3,
    status: {
      status: "on air",
      heure: "16:00",
      jour: "Samedi",
      lastSaison: 3,
      lastEpisode: 5,
    },
    studio: "Pierrot",
  },
  {
    id: 44,
    name: "Bungo Stray Dogs",
    img: "/img/bsd.jpg",
    genre: ["Action", "Mystère"],
    nbSaison: 5,
    status: { status: "none" },
    studio: "Bones",
  },
  {
    id: 45,
    name: "Fate/Stay Night: UBW",
    img: "/img/fate.jpg",
    genre: ["Action", "Magie"],
    nbSaison: 2,
    status: { status: "none" },
    studio: "ufotable",
  },
  {
    id: 46,
    name: "Pluto",
    img: "/img/pluto.jpg",
    genre: ["Sci-Fi", "Psychologique"],
    nbSaison: 1,
    status: { status: "none" },
    studio: "Studio M2",
  },
  {
    id: 47,
    name: "Neon Genesis Evangelion",
    img: "/img/eva.jpg",
    genre: ["Mecha", "Psychologique"],
    nbSaison: 1,
    status: { status: "none" },
    studio: "Gainax",
  },
  {
    id: 48,
    name: "Cowboy Bebop",
    img: "/img/bebop.jpg",
    genre: ["Sci-Fi", "Action"],
    nbSaison: 1,
    status: { status: "none" },
    studio: "Sunrise",
  },
  {
    id: 49,
    name: "The Eminence in Shadow",
    img: "/img/shadow.jpg",
    genre: ["Action", "Comédie"],
    nbSaison: 2,
    status: { status: "none" },
    studio: "Nexus",
  },
  {
    id: 50,
    name: "Uzumaki",
    img: "/img/uzumaki.jpg",
    genre: ["Horreur", "Surnaturel"],
    nbSaison: 1,
    status: { status: "none" },
    studio: "Drive",
  },
])
    const DataFiltered = ref(Data)

export const useCatalogfilter = () => {

    const filterOptions = () => {
        const filterO = {
            genre:[],
            status:[],
        }
        Data.value.forEach(ele => {
            ele.genre.forEach(e => {
                 if(!filterO.genre.includes(e)){
                    filterO.genre.push(e)
            }
            })

            if(!filterO.status.includes(ele.status.status)){
                filterO.status.push(ele.status.status)
            }
            
        
        });
        
        return filterO;

        
    }


    return {
        textFilter,
        contentfilter,
        Data,
        DataFiltered,
        filterOptions,
    }
}